# -*- coding: utf-8 -*-
"""ai_model(2)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qGsY57QBs9SUaJrza2UHfecwH4J1cJvh
"""

import os
import torch
import torchvision
from torch import nn
from torch.autograd import Variable
from torch.utils.data import Dataset, DataLoader
from torchtext import data
from torchtext.data import TabularDataset
import numpy as np
import pandas as pd

new_user_input = torch.FloatTensor([0, 0, 0, 3, 1, 2])
output = model(new_user_input)

output = (output + 1)
print(output)

# 주어진 테이블
food_table = []

print("모델 Output")
print(output)

print("최고 별점 음식 추천")
print(np.sort(output.detach().numpy()))

print("최고 별점의 food id 리스트")
sort_food_id = np.argmax(output.detach().numpy())
print(sort_food_id)

print("최고 별점의 food name 리스트")
print(food_table[sort_food_id])